---                          

- name: Find wars checksum
  find:
    path: /usr/WebSphere/wlp/usr/servers/b1_443_api/apps
    patterns: '*.war'
    get_checksum: yes
  register: server_war_files         
- debug:
    msg: 
      - "{{ server_war_files }}"
  #when: p.stat.isdir is defined and p.stat.isdir
- name: item.0 returns from the first list, item.1 returns from the second list
  debug:
    msg: "{{ item.0 }},{{ item.1 }}"
  with_together:
    - "{{ server_war_files.files | json_query('[].path[]') | list }}"
    - "{{ server_war_files.files | json_query('[].checksum[]') | list }}"
  register: debug_out

- debug:
    msg: 
      - "{{ debug_out.results | map(attribute='msg') | list }}"

- name: "Output Information to PROD_WARS_{{ lookup('env','WORKSPACE') }}/{{ lookup('pipe','date +%Y%m%d') }}_{{ lookup('env','BUILD_ID') }}.csv"
  lineinfile:
    dest: "{{ lookup('env','WORKSPACE') }}/PROD_WARS_{{ lookup('pipe','date +%Y%m%d') }}_{{ lookup('env','BUILD_ID') }}.csv"
    line: "{{ debug_out.results | map(attribute='msg') | list }}"
    create: true
    state: present
  delegate_to: localhost

# - name: Remove single quotes
#   replace:
#     path: "OUT_{{ lookup('pipe','date +%Y%m%d') }}.csv"
#     regexp: "'"
#     replace: ""
#   delegate_to: localhost

# - name: Replace comma-space with comma.
#   replace:
#     path: "OUT_{{ lookup('pipe','date +%Y%m%d') }}.csv"
#     regexp: ", "
#     replace: ","
#   delegate_to: localhost        